// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProLab.Data;

namespace ProLab.Migrations
{
    [DbContext(typeof(ProLabContext))]
    [Migration("20210306191409_EmployeesAdded")]
    partial class EmployeesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ProLab.ImageUpload.Models.ImageModel", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HockeyGameId")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ImageId");

                    b.HasIndex("HockeyGameId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.ActivityPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityPostStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTimeChanged")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeEnded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimePosted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeStarted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HealthActivityId")
                        .HasColumnType("int");

                    b.Property<int>("HoursSpent")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinutesSpent")
                        .HasColumnType("int");

                    b.Property<int>("SecondsSpent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityPostStatusId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("HealthActivityId");

                    b.ToTable("ActivityPosts");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.ActivityPostStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityPostStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivityPostStatuses");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.Aktivitet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AktivitetsBeskrivning")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aktivitet");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ssn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArenaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArenaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Arena");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.CSPStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CSPStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CSPStatus");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.CleverServicePayments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CSPStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Payment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PaymentBeforeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CSPStatusId");

                    b.HasIndex("ClubId");

                    b.ToTable("CleverServicePayments");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClubName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClubNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Club");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyRoleId");

                    b.HasIndex("CompanyStatusId");

                    b.HasIndex("CompanyTypeId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.CompanyRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyRoles");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.CompanyStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyStatuses");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.CompanyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyTypes");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTimeChanged")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.GameCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GameCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameCategory");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.GameStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GameStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameStatus");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.GameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GameTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameType");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.HealthActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HealthActivityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KcalPerHour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HealthActivities");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.HockeyGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArenaId")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTeamScore")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateTimeChanged")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimePosted")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GameCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("GameTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamScore")
                        .HasColumnType("int");

                    b.Property<int?>("RefereeId")
                        .HasColumnType("int");

                    b.Property<int?>("RefereeId1")
                        .HasColumnType("int");

                    b.Property<int?>("RefereeId2")
                        .HasColumnType("int");

                    b.Property<int?>("RefereeId3")
                        .HasColumnType("int");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("TSMNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("ClubId");

                    b.HasIndex("ClubId1");

                    b.HasIndex("GameCategoryId");

                    b.HasIndex("GameStatusId");

                    b.HasIndex("GameTypeId");

                    b.HasIndex("RefereeId");

                    b.HasIndex("RefereeId1");

                    b.HasIndex("RefereeId2");

                    b.HasIndex("RefereeId3");

                    b.HasIndex("SeriesId");

                    b.ToTable("HockeyGame");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.MDProtocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BodyTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diarrhea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilySymtoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Headache")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuscleAches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NasalCongestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nausea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherSymptoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherSymptomsDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RefereeId")
                        .HasColumnType("int");

                    b.Property<string>("SoreThroat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RefereeId");

                    b.ToTable("MDProtocol");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.PlanPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AktivitetId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTimeChanged")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlanedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AktivitetId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("PlanPost");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.ProjectPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateTimeChanged")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeDone")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimePlaned")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimePosted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeStarted")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HourPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LabourCostActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MtrCostActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectPostDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectPostStatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TimeActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TimeEstimate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCostActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCostEstimate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectPostStatusId");

                    b.ToTable("ProjectPosts");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.ProjectPostStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectPostStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectPostStatus");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.RefFees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UDZ")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("RefFees");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.RefRecStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RefRecStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefRecStatus");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.RefReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AllowanceHD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AllowanceHD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AllowanceLD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AllowanceLD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescriptionOthersHD1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionOthersHD2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionOthersLD1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionOthersLD2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GameFeeHD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GameFeeHD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GameFeeLD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GameFeeLD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("HockeyGameId")
                        .HasColumnType("int");

                    b.Property<decimal>("KmHD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KmHD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KmLD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KmLD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LostErningsHD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LostErningsHD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LostErningsLD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LostErningsLD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherHD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherHD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherLD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherLD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RefRecStatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCostHD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCostHD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCostHalfHockeyGame")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCostHockeyGame")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCostLD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCostLD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TravelExpensesHD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TravelExpensesHD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TravelExpensesLD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TravelExpensesLD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TravelSalarySupplementHD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TravelSalarySupplementHD2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TravelSalarySupplementLD1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TravelSalarySupplementLD2")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HockeyGameId");

                    b.HasIndex("RefRecStatusId");

                    b.ToTable("RefReceipt");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.Referee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrivateEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ssn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwishNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Referee");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SeriesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeriesNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeriesPlayTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.TSMGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArenaId")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTeamScore")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTimeChanged")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimePosted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GameDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HomeTeamScore")
                        .HasColumnType("int");

                    b.Property<int?>("RefereeId")
                        .HasColumnType("int");

                    b.Property<int?>("RefereeId1")
                        .HasColumnType("int");

                    b.Property<int?>("RefereeId2")
                        .HasColumnType("int");

                    b.Property<int?>("RefereeId3")
                        .HasColumnType("int");

                    b.Property<string>("TSMNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TSMSeriesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("ClubId");

                    b.HasIndex("ClubId1");

                    b.HasIndex("RefereeId");

                    b.HasIndex("RefereeId1");

                    b.HasIndex("RefereeId2");

                    b.HasIndex("RefereeId3");

                    b.HasIndex("TSMSeriesId");

                    b.ToTable("TSMGames");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.TSMHocekyGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Arena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateChanged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GameDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameStatusId")
                        .HasColumnType("int");

                    b.Property<string>("HD1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HD2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LD1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LD2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Round")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Series")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supervisor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameStatusId");

                    b.ToTable("TSMHockeyGame");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.TSMSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TSMSeriesName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TSMSeries");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProLab.Models.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProLab.ImageUpload.Models.ImageModel", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.HockeyGame", "HockeyGame")
                        .WithMany()
                        .HasForeignKey("HockeyGameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HockeyGame");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.ActivityPost", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.ActivityPostStatus", "ActivityPostStatus")
                        .WithMany()
                        .HasForeignKey("ActivityPostStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProLab.Models.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.HealthActivity", "HealthActivity")
                        .WithMany()
                        .HasForeignKey("HealthActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivityPostStatus");

                    b.Navigation("HealthActivity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.CleverServicePayments", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.CSPStatus", "CSPStatus")
                        .WithMany()
                        .HasForeignKey("CSPStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Club");

                    b.Navigation("CSPStatus");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.Company", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.CompanyRole", "CompanyRole")
                        .WithMany()
                        .HasForeignKey("CompanyRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.CompanyStatus", "CompanyStatus")
                        .WithMany()
                        .HasForeignKey("CompanyStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.CompanyType", "CompanyType")
                        .WithMany()
                        .HasForeignKey("CompanyTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompanyRole");

                    b.Navigation("CompanyStatus");

                    b.Navigation("CompanyType");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.Employee", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.HockeyGame", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.Arena", "Arena")
                        .WithMany()
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Club", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Club", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("ClubId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.GameCategory", "GameCategory")
                        .WithMany()
                        .HasForeignKey("GameCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.GameStatus", "GameStatus")
                        .WithMany()
                        .HasForeignKey("GameStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.GameType", "GameType")
                        .WithMany()
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Referee", "HD1")
                        .WithMany()
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Referee", "HD2")
                        .WithMany()
                        .HasForeignKey("RefereeId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Referee", "LD1")
                        .WithMany()
                        .HasForeignKey("RefereeId2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Referee", "LD2")
                        .WithMany()
                        .HasForeignKey("RefereeId3")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Arena");

                    b.Navigation("AwayTeam");

                    b.Navigation("GameCategory");

                    b.Navigation("GameStatus");

                    b.Navigation("GameType");

                    b.Navigation("HD1");

                    b.Navigation("HD2");

                    b.Navigation("HomeTeam");

                    b.Navigation("LD1");

                    b.Navigation("LD2");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.MDProtocol", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.Referee", "Referee")
                        .WithMany()
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.PlanPost", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.Aktivitet", "Aktivitet")
                        .WithMany()
                        .HasForeignKey("AktivitetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProLab.Models.DataModels.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aktivitet");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.ProjectPost", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.ProjectPostStatus", "Status")
                        .WithMany()
                        .HasForeignKey("ProjectPostStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.RefReceipt", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.HockeyGame", "HockeyGame")
                        .WithMany()
                        .HasForeignKey("HockeyGameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.RefRecStatus", "RefRecStatus")
                        .WithMany()
                        .HasForeignKey("RefRecStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HockeyGame");

                    b.Navigation("RefRecStatus");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.Referee", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.TSMGame", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.Arena", "Arena")
                        .WithMany()
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Club", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Club", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("ClubId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Referee", "HD1")
                        .WithMany()
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Referee", "HD2")
                        .WithMany()
                        .HasForeignKey("RefereeId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Referee", "LD1")
                        .WithMany()
                        .HasForeignKey("RefereeId2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.Referee", "LD2")
                        .WithMany()
                        .HasForeignKey("RefereeId3")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Models.DataModels.TSMSeries", "TSMSeries")
                        .WithMany()
                        .HasForeignKey("TSMSeriesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Arena");

                    b.Navigation("AwayTeam");

                    b.Navigation("HD1");

                    b.Navigation("HD2");

                    b.Navigation("HomeTeam");

                    b.Navigation("LD1");

                    b.Navigation("LD2");

                    b.Navigation("TSMSeries");
                });

            modelBuilder.Entity("ProLab.Models.DataModels.TSMHocekyGame", b =>
                {
                    b.HasOne("ProLab.Models.DataModels.GameStatus", "GameStatus")
                        .WithMany()
                        .HasForeignKey("GameStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GameStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
